//! Raw FFI bindings to librist, auto-generated by `bindgen`.
//!
//! This crate wraps the vendored librist C library, providing access to
//! RIST sender/receiver contexts, peer management, stats callbacks, and
//! data read/write operations.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
